[build]
  publish = "."

[build.environment]
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

[functions]
  directory = "netlify/functions"

[functions."daily-reminders"]
  schedule = "0 0 * * *"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
